// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package client

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"da": &dictionary{index: daIndex, data: daData},
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
		"es": &dictionary{index: esIndex, data: esData},
		"fr": &dictionary{index: frIndex, data: frData},
		"it": &dictionary{index: itIndex, data: itData},
		"nl": &dictionary{index: nlIndex, data: nlData},
		"sl": &dictionary{index: slIndex, data: slData},
		"uk": &dictionary{index: ukIndex, data: ukData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"An internal error occurred":                                                                    4,
	"Failed to add a secure internet server with organisation ID: '%s'":                             6,
	"Failed to add a server with URL: '%s'":                                                         7,
	"Failed to add an institute access server with URL: '%s'":                                       5,
	"Failed to connect to server: '%s'":                                                             9,
	"Failed to obtain a VPN configuration for server: '%s'":                                         10,
	"Failed to obtain the list of organizations":                                                    11,
	"Failed to obtain the list of servers":                                                          12,
	"The client tried to autoconnect to the VPN server: '%s', but the operation failed to complete": 1,
	"The client tried to autoconnect to the VPN server: '%s', but you need to authorizate again. Please manually connect again": 0,
	"The input: '%s' is not a valid URL":                  8,
	"timeout reached for URL: '%s' and HTTP method: '%s'": 2,
	"with cause:": 3,
}

var daIndex = []uint32{ // 14 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 80 bytes

const daData string = ""

var deIndex = []uint32{ // 14 elements
	0x00000000, 0x000000a6, 0x0000012c, 0x00000173,
	0x00000180, 0x000001a4, 0x000001a4, 0x000001a4,
	0x000001a4, 0x000001a4, 0x000001a4, 0x000001a4,
	0x000001a4, 0x000001a4,
} // Size: 80 bytes

const deData string = "" + // Size: 420 bytes
	"\x02Der Client hat versucht, sich automatisch mit dem VPN-Server '%[1]s'" +
	" zu verbinden, aber Sie müssen sich erneut autorisieren. Bitte verbinden" +
	" sie sich manuell erneut\x02Der Client hat versucht, sich automatisch mi" +
	"t dem VPN-Server '%[1]s' zu verbinden, aber der Vorgang konnte nicht abg" +
	"eschlossen werden\x02Zeitüberschreitung für URL '%[1]s' und HTTP-Methode" +
	" '%[2]s' erreicht\x02mit Ursache:\x02Ein interner Fehler ist aufgetreten"

var enIndex = []uint32{ // 14 elements
	0x00000000, 0x0000007d, 0x000000de, 0x00000118,
	0x00000124, 0x0000013f, 0x0000017a, 0x000001bf,
	0x000001e8, 0x0000020e, 0x00000233, 0x0000026c,
	0x00000297, 0x000002bc,
} // Size: 80 bytes

const enData string = "" + // Size: 700 bytes
	"\x02The client tried to autoconnect to the VPN server: '%[1]s', but you " +
	"need to authorizate again. Please manually connect again\x02The client t" +
	"ried to autoconnect to the VPN server: '%[1]s', but the operation failed" +
	" to complete\x02timeout reached for URL: '%[1]s' and HTTP method: '%[2]s" +
	"'\x02with cause:\x02An internal error occurred\x02Failed to add an insti" +
	"tute access server with URL: '%[1]s'\x02Failed to add a secure internet " +
	"server with organisation ID: '%[1]s'\x02Failed to add a server with URL:" +
	" '%[1]s'\x02The input: '%[1]s' is not a valid URL\x02Failed to connect t" +
	"o server: '%[1]s'\x02Failed to obtain a VPN configuration for server: '%" +
	"[1]s'\x02Failed to obtain the list of organizations\x02Failed to obtain " +
	"the list of servers"

var esIndex = []uint32{ // 14 elements
	0x00000000, 0x0000008c, 0x000000ef, 0x00000134,
	0x00000143, 0x0000015c, 0x0000015c, 0x0000015c,
	0x0000015c, 0x0000015c, 0x0000015c, 0x0000015c,
	0x0000015c, 0x0000015c,
} // Size: 80 bytes

const esData string = "" + // Size: 348 bytes
	"\x02El cliente intentó autoconectarse al servidor VPN: '%[1]s', pero nec" +
	"esita autorizarse de nuevo. Por favor, conéctese manualmente de nuevo" +
	"\x02El cliente intentó autoconectarse al servidor VPN: %[1]s', pero la o" +
	"peración no se ha completado\x02tiempo de espera alcanzado para URL: '%[" +
	"1]s' y método HTTP: '%[2]s'\x02Por el motivo:\x02Se ha producido un erro" +
	"r"

var frIndex = []uint32{ // 14 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 80 bytes

const frData string = ""

var itIndex = []uint32{ // 14 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 80 bytes

const itData string = ""

var nlIndex = []uint32{ // 14 elements
	0x00000000, 0x00000087, 0x000000de, 0x00000130,
	0x0000013d, 0x0000015c, 0x0000015c, 0x0000015c,
	0x0000015c, 0x0000015c, 0x0000015c, 0x0000015c,
	0x0000015c, 0x0000015c,
} // Size: 80 bytes

const nlData string = "" + // Size: 348 bytes
	"\x02De client wilde automatisch verbinden met de VPN server: '%[1]s', ma" +
	"ar er is geen geldige authorizatie. Verbind handmatig nog een keer\x02De" +
	" client wilde automatisch verbinden met de VPN server: '%[1]s', maar het" +
	" was mislukt\x02Er heeft zich een time-out opgetreden voor URL: '%[1]s' " +
	"met HTTP methode: '%[2]s'\x02met oorzaak:\x02Een interne fout is opgetre" +
	"den"

var slIndex = []uint32{ // 14 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x0000000a, 0x00000028, 0x00000028, 0x00000028,
	0x00000028, 0x00000028, 0x00000028, 0x00000028,
	0x00000028, 0x00000028,
} // Size: 80 bytes

const slData string = "\x02; razlog:\x02Prišlo je do notranje napake"

var ukIndex = []uint32{ // 14 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 80 bytes

const ukData string = ""

// Total table size 2576 bytes (2KiB); checksum: 6AF0360C
